import React, { useState } from 'react';
import { X, Link2, Trash2, Plus, Github } from 'lucide-react';
import { useShop } from '../../context/ShopContext';
import { Button } from '../UI/Button';
import { Product } from '../../types';
import { METALS, GEMS } from '../../constants';

export const AdminPanel: React.FC = () => {
  const { isAdminOpen, setIsAdminOpen, products, addProduct, removeProduct } = useShop();
  const [activeTab, setActiveTab] = useState<'list' | 'add'>('list');

  // Form State
  const [formData, setFormData] = useState<Partial<Product>>({
    name: '',
    price: 0,
    description: '',
    category: 'Ring',
    metal: 'Gold',
    gem: 'Diamond',
    metalColor: METALS['Gold'].color,
    gemColor: GEMS['Diamond'].color,
    modelUrl: '' 
  });

  if (!isAdminOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    const newProduct: Product = {
        id: '', // Will be generated by Firebase
        name: formData.name || 'New Product',
        price: Number(formData.price) || 0,
        description: formData.description || '',
        category: formData.category as any,
        metal: formData.metal as any,
        gem: formData.gem as any,
        metalColor: METALS[formData.metal as keyof typeof METALS].color,
        gemColor: GEMS[formData.gem as keyof typeof GEMS].color,
        modelUrl: formData.modelUrl || undefined
    };

    addProduct(newProduct);
    
    // Reset Form
    setFormData({
        name: '', price: 0, description: '', category: 'Ring', metal: 'Gold', gem: 'Diamond',
        metalColor: METALS['Gold'].color, gemColor: GEMS['Diamond'].color, modelUrl: ''
    });
    setActiveTab('list');
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/80 backdrop-blur-sm">
      <div className="bg-zinc-900 w-full max-w-4xl h-[80vh] border border-zinc-800 shadow-2xl flex flex-col rounded-lg overflow-hidden">
        
        {/* Header */}
        <div className="h-16 border-b border-zinc-800 flex justify-between items-center px-6 bg-zinc-950">
            <h2 className="font-display text-xl text-white">Boutique Administration</h2>
            <button onClick={() => setIsAdminOpen(false)} className="text-zinc-500 hover:text-white">
                <X size={24} />
            </button>
        </div>

        <div className="flex flex-1 overflow-hidden">
            {/* Sidebar */}
            <div className="w-48 bg-zinc-950 border-r border-zinc-800 p-4 space-y-2">
                <button 
                    onClick={() => setActiveTab('list')}
                    className={`w-full text-left px-4 py-3 rounded text-sm ${activeTab === 'list' ? 'bg-gold-600/20 text-gold-400' : 'text-zinc-400 hover:bg-zinc-900'}`}
                >
                    Product List
                </button>
                <button 
                    onClick={() => setActiveTab('add')}
                    className={`w-full text-left px-4 py-3 rounded text-sm ${activeTab === 'add' ? 'bg-gold-600/20 text-gold-400' : 'text-zinc-400 hover:bg-zinc-900'}`}
                >
                    Add Product
                </button>
            </div>

            {/* Content Area */}
            <div className="flex-1 p-8 overflow-y-auto bg-zinc-900">
                
                {activeTab === 'list' && (
                    <div className="space-y-4">
                        <h3 className="text-white font-serif mb-6">Current Inventory (Cloud)</h3>
                        <div className="grid gap-4">
                            {products.map(p => (
                                <div key={p.id} className="bg-zinc-950 border border-zinc-800 p-4 flex justify-between items-center rounded">
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 bg-zinc-800 rounded flex items-center justify-center text-xs text-zinc-500 overflow-hidden">
                                            {p.modelUrl ? 'GLB' : 'PROC'}
                                        </div>
                                        <div>
                                            <h4 className="text-white font-display">{p.name}</h4>
                                            <p className="text-xs text-zinc-500">${p.price.toLocaleString()} • {p.metal} • {p.gem}</p>
                                        </div>
                                    </div>
                                    <button 
                                        onClick={() => removeProduct(p.id)}
                                        className="text-red-900 hover:text-red-500 transition-colors p-2"
                                        title="Delete Product"
                                    >
                                        <Trash2 size={18} />
                                    </button>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {activeTab === 'add' && (
                    <form onSubmit={handleSubmit} className="max-w-xl mx-auto space-y-6">
                        <h3 className="text-white font-serif mb-6">Add New Masterpiece</h3>
                        
                        <div className="space-y-4">
                            <div>
                                <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Product Name</label>
                                <input 
                                    type="text" 
                                    required
                                    value={formData.name}
                                    onChange={e => setFormData({...formData, name: e.target.value})}
                                    className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Price ($)</label>
                                    <input 
                                        type="number" 
                                        required
                                        value={formData.price}
                                        onChange={e => setFormData({...formData, price: Number(e.target.value)})}
                                        className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Category</label>
                                    <select 
                                        value={formData.category}
                                        onChange={e => setFormData({...formData, category: e.target.value as any})}
                                        className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                    >
                                        <option value="Ring">Ring</option>
                                        <option value="Necklace">Necklace</option>
                                        <option value="Earring">Earring</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Description</label>
                                <textarea 
                                    required
                                    value={formData.description}
                                    onChange={e => setFormData({...formData, description: e.target.value})}
                                    rows={3}
                                    className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Default Metal</label>
                                    <select 
                                        value={formData.metal}
                                        onChange={e => setFormData({...formData, metal: e.target.value as any})}
                                        className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                    >
                                        {Object.keys(METALS).map(m => <option key={m} value={m}>{m}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2">Default Gem</label>
                                    <select 
                                        value={formData.gem}
                                        onChange={e => setFormData({...formData, gem: e.target.value as any})}
                                        className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded"
                                    >
                                        {Object.keys(GEMS).map(g => <option key={g} value={g}>{g}</option>)}
                                    </select>
                                </div>
                            </div>

                            <div className="pt-4 border-t border-zinc-800">
                                <label className="block text-xs uppercase tracking-widest text-zinc-500 mb-2 flex items-center gap-2">
                                    <Link2 size={12} /> Model URL (GLB)
                                </label>
                                <div className="space-y-2">
                                    <input 
                                        type="url" 
                                        placeholder="https://raw.githubusercontent.com/username/repo/main/model.glb"
                                        value={formData.modelUrl}
                                        onChange={e => setFormData({...formData, modelUrl: e.target.value})}
                                        className="w-full bg-zinc-950 border border-zinc-800 p-3 text-white focus:border-gold-600 focus:outline-none rounded font-mono text-xs"
                                    />
                                    <p className="text-[10px] text-zinc-500">
                                        For GitHub, ensure you use the "Raw" file link (e.g., raw.githubusercontent.com).
                                    </p>
                                </div>
                            </div>
                        </div>

                        <Button type="submit" className="w-full">Create Product</Button>
                    </form>
                )}
            </div>
        </div>
      </div>
    </div>
  );
};
